// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJNIzHna74nq2spa2pq2tAFlhwohxEC9I',
    appId: '1:292881892467:android:6e71b8f536f77bfa23d606',
    messagingSenderId: '292881892467',
    projectId: 'volt-findev',
    storageBucket: 'volt-findev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpMBY1P0prh-GSPbKDBw_xwzWnew_geP4',
    appId: '1:292881892467:ios:43c1e6fa8123642d23d606',
    messagingSenderId: '292881892467',
    projectId: 'volt-findev',
    storageBucket: 'volt-findev.firebasestorage.app',
    iosBundleId: 'com.example.voltFind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpMBY1P0prh-GSPbKDBw_xwzWnew_geP4',
    appId: '1:292881892467:ios:43c1e6fa8123642d23d606',
    messagingSenderId: '292881892467',
    projectId: 'volt-findev',
    storageBucket: 'volt-findev.firebasestorage.app',
    iosBundleId: 'com.example.voltFind',
  );
}
